export const TIME_CONSTANTS = {
    ACCESS_TOKEN_EXPIRE: process.env.ACCESS_TOKEN_EXPIRE || '3h',
    REFRESH_TOKEN_EXPIRE: process.env.REFRESH_TOKEN_EXPIRE || '7d',
    REFRESH_TOKEN_EXPIRE_DAYS: +process.env.REFRESH_TOKEN_EXPIRE_DAYS || 7,
};
